import { defineConfig } from 'vitest/config'
import solidPlugin from 'vite-plugin-solid'
import tailwindcss from '@tailwindcss/vite'

export default defineConfig({
  plugins: [solidPlugin({ hot: false }), tailwindcss()],
  test: {
    environment: 'happy-dom',
    globals: true,
    // Node ≥22.4 ships an experimental `localStorage` global that is disabled
    // by default. Vitest's happy-dom env won't override it, so tests using
    // localStorage fail with "localStorage is not available". Disable it so
    // happy-dom's real Storage is installed instead.
    execArgv: ['--no-webstorage'],
    setupFiles: [],
    include: ['src/**/*.test.ts', 'src/**/*.test.tsx'],
    exclude: ['node_modules', 'dist', '.wrangler'],
    coverage: {
      provider: 'v8',
      reporter: ['text', 'text-summary'],
      include: ['src/**/*.{ts,tsx}'],
      exclude: [
        'src/**/*.test.ts',
        'src/**/*.test.tsx',
        'src/routeTree.gen.ts', // generated by TanStack Router
        'src/main.tsx',
        'src/router.tsx',
        // Type-only modules (no executable code) — report 0% misleadingly
        'src/types.ts',
        'src/types/ws.ts',
      ],
      thresholds: {
        statements: 90,
        branches: 78,
        functions: 85,
        lines: 92,
      },
    },
  },
  resolve: {
    alias: {
      // cloudflare:workers is only available in Workers runtime, not in vitest
      'cloudflare:workers': '@cloudflare/workers-types',
    },
  },
})
