-- 500 Pertanyaan Truth — Beragam: ringan, lucu, spicy, deep
-- Dirancang untuk teman dan pasangan
INSERT OR IGNORE INTO questions (id, type, text) VALUES
('t001', 'truth', 'Apa hal pertama yang kamu pikirkan saat bangun tidur?'),
('t002', 'truth', 'Apa makanan favoritmu sepanjang masa?'),
('t003', 'truth', 'Apa film yang bisa kamu tonton berulang kali tanpa bosan?'),
('t004', 'truth', 'Siapa orang yang paling kamu kagumi di dunia?'),
('t005', 'truth', 'Apa ketakutan terbesar kamu?'),
('t006', 'truth', 'Apa kebiasaan buruk yang paling susah kamu hilangkan?'),
('t007', 'truth', 'Apa lagu yang paling kamu hafal liriknya?'),
('t008', 'truth', 'Apa tempat paling indah yang pernah kamu kunjungi?'),
('t009', 'truth', 'Apa hal paling memalukan yang pernah kamu alami?'),
('t010', 'truth', 'Apa rahasia kecil yang belum pernah kamu ceritakan ke siapa pun?'),
('t011', 'truth', 'Apa yang lebih penting: uang atau kebahagiaan?'),
('t012', 'truth', 'Siapa cinta pertamamu?'),
('t013', 'truth', 'Apa hal terbodoh yang pernah kamu lakukan karena cinta?'),
('t014', 'truth', 'Apa aplikasi di HP-mu yang paling sering kamu buka?'),
('t015', 'truth', 'Apa skill aneh atau tidak berguna yang kamu miliki?'),
('t016', 'truth', 'Apa kenangan masa kecil favoritmu?'),
('t017', 'truth', 'Apa yang paling kamu sesali dalam hidup?'),
('t018', 'truth', 'Apa mimpi teraneh yang pernah kamu ingat?'),
('t019', 'truth', 'Apa hal yang paling kamu suka dari dirimu sendiri?'),
('t020', 'truth', 'Apa hal yang paling tidak kamu suka dari dirimu sendiri?'),
('t021', 'truth', 'Jika bisa menjadi hewan selama sehari, hewan apa yang kamu pilih?'),
('t022', 'truth', 'Apa yang paling membuatmu stres akhir-akhir ini?'),
('t023', 'truth', 'Apa pencapaian yang paling kamu banggakan?'),
('t024', 'truth', 'Siapa temanmu yang paling mempengaruhi hidupmu?'),
('t025', 'truth', 'Apa hal paling berani yang pernah kamu lakukan?'),
('t026', 'truth', 'Apa satu keinginan yang ingin kamu wujudukan dalam 5 tahun ke depan?'),
('t027', 'truth', 'Apa hal tentangmu yang sering disalahpahami orang lain?'),
('t028', 'truth', 'Apa hal paling ekstrem yang pernah kamu lakukan?'),
('t029', 'truth', 'Apa yang pertama kali kamu lihat dari seseorang saat baru kenal?'),
('t030', 'truth', 'Apa buku atau film yang paling mempengaruhi cara berpikirmu?'),
('t031', 'truth', 'Apa yang akan kamu lakukan jika menang lotre 10 miliar?'),
('t032', 'truth', 'Apa hal kecil yang bisa membuat harimu langsung lebih baik?'),
('t033', 'truth', 'Apa yang paling kamu rindukan dari masa kecilmu?'),
('t034', 'truth', 'Apa yang biasa kamu lakukan saat tidak ada yang melihat?'),
('t035', 'truth', 'Apa ketakutan irasional yang kamu miliki?'),
('t036', 'truth', 'Apa satu hal yang ingin kamu ubah dari dirimu?'),
('t037', 'truth', 'Siapa orang yang paling membuatmu tertawa?'),
('t038', 'truth', 'Apa hal paling berharga yang kamu miliki?'),
('t039', 'truth', 'Apa pelajaran hidup paling berharga yang pernah kamu dapatkan?'),
('t040', 'truth', 'Apa yang kamu cari dalam sebuah pertemanan?'),
('t041', 'truth', 'Apa definisi kebahagiaan versimu?'),
('t042', 'truth', 'Kapan terakhir kali kamu menangis?'),
('t043', 'truth', 'Apa yang membuatmu menangis?'),
('t044', 'truth', 'Apa tempat favoritmu untuk menyendiri?'),
('t045', 'truth', 'Apa hal yang paling kamu takutkan tentang masa depan?'),
('t046', 'truth', 'Apa satu kebiasaan yang ingin kamu mulai lakukan?'),
('t047', 'truth', 'Apa satu kebiasaan yang ingin kamu hentikan?'),
('t048', 'truth', 'Siapa orang yang paling jujur menurutmu?'),
('t049', 'truth', 'Apa kualitas terpenting dalam seorang pemimpin?'),
('t050', 'truth', 'Apa yang lebih penting: penampilan atau kepribadian?'),
('t051', 'truth', 'Apa yang akan kamu lakukan jika kamu tidak bisa tidur semalaman?'),
('t052', 'truth', 'Apa makanan paling aneh yang pernah kamu makan?'),
('t053', 'truth', 'Apa yang akan kamu bawa jika terdampar di pulau terpencil?'),
('t054', 'truth', 'Apa hal pertama yang akan kamu beli jika kaya raya?'),
('t055', 'truth', 'Apa hal paling berisiko yang pernah kamu lakukan?'),
('t056', 'truth', 'Apa yang paling kamu banggakan dari keluargamu?'),
('t057', 'truth', 'Apa satu hal yang diajarkan orang tuamu yang masih kamu pegang?'),
('t058', 'truth', 'Apa yang lebih menakutkan: kegagalan atau penyesalan?'),
('t059', 'truth', 'Apa satu tempat yang ingin kamu kunjungi sebelum mati?'),
('t060', 'truth', 'Apa yang lebih penting: ambisi atau ketenangan?'),
('t061', 'truth', 'Apa lagu yang bisa mewakili hidupmu saat ini?'),
('t062', 'truth', 'Apa yang akan kamu katakan ke dirimu yang berusia 10 tahun?'),
('t063', 'truth', 'Apa yang akan kamu katakan ke dirimu yang berusia 50 tahun?'),
('t064', 'truth', 'Apa superpower yang paling ingin kamu miliki?'),
('t065', 'truth', 'Apa yang lebih kamu takuti: ketinggian atau kegelapan?'),
('t066', 'truth', 'Apa hal terbaik yang pernah terjadi padamu secara tiba-tiba?'),
('t067', 'truth', 'Apa yang paling kamu tunggu-tunggu saat ini?'),
('t068', 'truth', 'Apa satu hal yang membuatmu merasa dewasa?'),
('t069', 'truth', 'Apa yang paling membuatmu bersemangat akhir-akhir ini?'),
('t070', 'truth', 'Apa satu hobi yang ingin kamu coba tapi belum sempat?'),
('t071', 'truth', 'Apa pertanyaan yang paling sering kamu dapatkan dari orang lain?'),
('t072', 'truth', 'Apa kebohongan terbesar yang pernah kamu katakan?'),
('t073', 'truth', 'Apa hal yang paling tidak kamu sukai dari orang lain?'),
('t074', 'truth', 'Apa sifat yang paling kamu suka dari orang lain?'),
('t075', 'truth', 'Apa yang akan kamu lakukan jika kamu menjadi presiden sehari?'),
('t076', 'truth', 'Apa yang lebih kamu suka: petualangan atau kenyamanan?'),
('t077', 'truth', 'Apa hal yang paling kamu rindukan dari masa sebelum pandemi?'),
('t078', 'truth', 'Apa satu keputusan terbaik yang pernah kamu buat?'),
('t079', 'truth', 'Apa satu keputusan terburuk yang pernah kamu buat?'),
('t080', 'truth', 'Apa yang ingin kamu capai sebelum usia 30?'),
('t081', 'truth', 'Apa hal paling konyol yang pernah kamu lakukan di depan umum?'),
('t082', 'truth', 'Apa yang paling sering kamu search di Google?'),
('t083', 'truth', 'Apa meme atau video viral yang paling kamu suka?'),
('t084', 'truth', 'Apa hal yang paling membuatmu malu sampai sekarang?'),
('t085', 'truth', 'Apa kebiasaan unik yang kamu lakukan sebelum tidur?'),
('t086', 'truth', 'Apa reality show paling memalukan yang kamu tonton?'),
('t087', 'truth', 'Apa hal yang paling sering kamu lakukan di kamar mandi?'),
('t088', 'truth', 'Apa barang yang paling aneh di kamarmu?'),
('t089', 'truth', 'Apa yang lebih memalukan: ketahuan bernyanyi atau ketahuan ngedance?'),
('t090', 'truth', 'Apa stiker atau emoji favoritmu?'),
('t091', 'truth', 'Apa yang akan kamu lakukan jika kamu jadi invisible selama sehari?'),
('t092', 'truth', 'Apa makanan combonyang paling aneh yang kamu suka?'),
('t093', 'truth', 'Apa yang terlintas di pikiranmu saat bangun tengah malam?'),
('t094', 'truth', 'Apa yang paling sering kamu lakukan di sosial media?'),
('t095', 'truth', 'Apa yang lebih memalukan: orang tua ngomong norak di depan teman atau mantan?'),
('t096', 'truth', 'Apa film horor yang paling membuatmu trauma?'),
('t097', 'truth', 'Apa yang akan kamu lakukan jika kamu jadi karakter di film favoritmu?'),
('t098', 'truth', 'Apa hal terbodoh yang pernah kamu percaya?'),
('t099', 'truth', 'Apa lelucon paling receh yang kamu tahu?'),
('t100', 'truth', 'Apa yang akan kamu lakukan jika semua orang di dunia bisu selama sehari?'),
('t101', 'truth', 'Apa pose foto paling konyol yang pernah kamu lakukan?'),
('t102', 'truth', 'Apa yang lebih buruk: terlambat 2 jam atau datang 2 jam lebih awal?'),
('t103', 'truth', 'Apa hal yang tidak bisa kamu lakukan padahal kelihatannya mudah?'),
('t104', 'truth', 'Apa tempat paling aneh di mana kamu pernah ketiduran?'),
('t105', 'truth', 'Apa yang paling memalukan di riwayat pencarianmu?'),
('t106', 'truth', 'Apa baju paling aneh yang pernah kamu pakai di depan umum?'),
('t107', 'truth', 'Apa yang akan kamu lakukan jika kamu jadi selebriti selama sehari?'),
('t108', 'truth', 'Apa suara paling memalukan yang bisa kamu buat?'),
('t109', 'truth', 'Apa yang akan kamu bawa ke acara \"pakaian paling aneh\"?'),
('t110', 'truth', 'Apa yang lebih memalukan: salah kirim chat atau salah nyanyi di karaoke?'),
('t111', 'truth', 'Apa yang akan kamu lakukan jika punya ekor selama sehari?'),
('t112', 'truth', 'Apa mimpi paling aneh yang pernah kamu ceritakan?'),
('t113', 'truth', 'Apa yang akan kamu lakukan jika semua hewan bisa bicara?'),
('t114', 'truth', 'Apa yang lebih aneh: kaus kaki beda warna atau baju dipakai terbalik?'),
('t115', 'truth', 'Apa kecelakaan kecil paling konyol yang pernah kamu alami?'),
('t116', 'truth', 'Apa yang akan kamu lakukan jika setiap kali bersin kamu ganti gender?'),
('t117', 'truth', 'Apa yang lebih lucu: kucing jatuh atau bayi tertawa?'),
('t118', 'truth', 'Apa yang akan kamu lakukan jika semua rambutmu rontok besok?'),
('t119', 'truth', 'Apa yang lebih buruk: gigi patah saat selfie atau jerawat di hidup saat wawancara?'),
('t120', 'truth', 'Apa yang lebih bahaya: kamu nyetir ngantuk atau kamu masak lapar?'),
('t121', 'truth', 'Apa yang paling tidak bisa kamu lupakan saat pertama kali pacaran?'),
('t122', 'truth', 'Apa kencan paling aneh yang pernah kamu alami?'),
('t123', 'truth', 'Apa yang lebih penting: chemistry atau kenyamanan?'),
('t124', 'truth', 'Apa pertanda kamu mulai suka sama seseorang?'),
('t125', 'truth', 'Apa hal paling romantis yang pernah kamu lakukan?'),
('t126', 'truth', 'Apa hal paling romantis yang pernah dilakukan orang lain untukmu?'),
('t127', 'truth', 'Apa yang lebih berat: LDR atau putus?'),
('t128', 'truth', 'Apa yang pertama kamu perhatikan dari lawan jenis?'),
('t129', 'truth', 'Apa yang lebih penting dalam hubungan: kejujuran atau kesetiaan?'),
('t130', 'truth', 'Apa sifat yang paling membuatmu tertarik pada seseorang?'),
('t131', 'truth', 'Apa hal yang paling mengganggu saat pacaran?'),
('t132', 'truth', 'Apa tipe pasangan idealmu?'),
('t133', 'truth', 'Apa yang akan kamu lakukan jika pasanganmu lupa ulang tahunmu?'),
('t134', 'truth', 'Apa yang lebih sakit: dikhianati teman atau dikhianati pacar?'),
('t135', 'truth', 'Apa lagu cinta favoritmu?'),
('t136', 'truth', 'Apa film romantis favoritmu?'),
('t137', 'truth', 'Apa definisi "cinta" versimu?'),
('t138', 'truth', 'Apa yang lebih penting: gairah atau stabilitas dalam hubungan?'),
('t139', 'truth', 'Apa hal yang paling kamu takutkan dalam suatu hubungan?'),
('t140', 'truth', 'Apa yang akan kamu lakukan jika pasanganmu tidak disukai teman-temanmu?'),
('t141', 'truth', 'Apa kado paling berkesan yang pernah kamu terima?'),
('t142', 'truth', 'Apa kado paling berkesan yang pernah kamu berikan?'),
('t143', 'truth', 'Apa hal yang paling bikin betah sama seseorang?'),
('t144', 'truth', 'Apa yang lebih menyenangkan: dikejar atau mengejar?'),
('t145', 'truth', 'Apa yang akan kamu lakukan jika mantanmu tiba-tiba chat?'),
('t146', 'truth', 'Apa hal yang tidak bisa ditoleransi dalam hubungan?'),
('t147', 'truth', 'Apa yang lebih penting: fisik atau kepribadian?'),
('t148', 'truth', 'Apa bentuk kasih sayang yang paling kamu suka?'),
('t149', 'truth', 'Apa yang akan kamu lakukan jika kamu dan pasanganmu punya zodiak yang bertentangan?'),
('t150', 'truth', 'Apa yang lebih serius: flirting atau friendzone?'),
('t151', 'truth', 'Apa helah yang paling kamu syukuri dalam hidup?'),
('t152', 'truth', 'Apa kejutan terbesar yang pernah kamu alami?'),
('t153', 'truth', 'Apa yang akan kamu lakukan jika bisa memutar waktu?'),
('t154', 'truth', 'Apa yang akan kamu lakukan jika bisa membaca pikiran orang?'),
('t155', 'truth', 'Apa yang lebih penting: masa lalu atau masa depan?'),
('t156', 'truth', 'Apa yang akan kamu lakukan jika tahu hari ini adalah hari terakhirmu?'),
('t157', 'truth', 'Apa yang lebih berharga: pengalaman atau materi?'),
('t158', 'truth', 'Apa nasihat paling berharga yang pernah kamu terima?'),
('t159', 'truth', 'Apa yang lebih menakutkan: gagal atau tidak pernah mencoba?'),
('t160', 'truth', 'Apa yang akan kamu lakukan jika semua orang jujur selama sehari?'),
('t161', 'truth', 'Apa yang akan kamu lakukan jika bisa menghilangkan satu emosi?'),
('t162', 'truth', 'Apa yang lebih sulit: memaafkan atau melupakan?'),
('t163', 'truth', 'Apa yang akan kamu lakukan jika bisa bertanya satu hal ke masa depan?'),
('t164', 'truth', 'Apa yang lebih berarti: perjuangan atau hasil?'),
('t165', 'truth', 'Apa satu hal yang belum kamu maafkan pada dirimu sendiri?'),
('t166', 'truth', 'Apa yang akan kamu lakukan jika bisa memulai hidup dari awal?'),
('t167', 'truth', 'Apa yang lebih mengubah hidupmu: kegagalan atau kesuksesan?'),
('t168', 'truth', 'Apa yang akan kamu lakukan jika tahu semua orang akan memaafkanmu?'),
('t169', 'truth', 'Apa yang paling kamu sesali tidak kamu lakukan?'),
('t170', 'truth', 'Apa kebenaran yang paling sulit kamu terima?'),
('t171', 'truth', 'Siapa yang paling kamu percaya di dunia ini?'),
('t172', 'truth', 'Apa yang lebih sulit: menerima bantuan atau meminta bantuan?'),
('t173', 'truth', 'Apa yang akan kamu lakukan jika tidak ada yang menghakimimu?'),
('t174', 'truth', 'Apa yang lebih membuatmu tumbuh: kesenangan atau kesulitan?'),
('t175', 'truth', 'Apa yang akan kamu lakukan jika punya kekuatan untuk menyembuhkan?'),
('t176', 'truth', 'Apa yang lebih penting: menjadi benar atau menjadi bahagia?'),
('t177', 'truth', 'Apa yang akan kamu ubah dari dunia ini jika bisa?'),
('t178', 'truth', 'Apa yang lebih membuatmu berarti: apa yang kamu lakukan atau siapa dirimu?'),
('t179', 'truth', 'Apa yang akan kamu lakukan jika bisa melihat masa depan?'),
('t180', 'truth', 'Apa satu hal yang membuatmu bangga menjadi dirimu?'),
('t181', 'truth', 'Apa yang lebih aneh: punya ingatan foto atau bisa dengar warna?'),
('t182', 'truth', 'Apa yang akan kamu lakukan jika semua orang bisa telepati?'),
('t183', 'truth', 'Apa yang lebih mengerikan: zombie atau vampir?'),
('t184', 'truth', 'Apa yang akan kamu lakukan jika bumi mulai berputar mundur?'),
('t185', 'truth', 'Apa yang lebih keren: jadi superhero yang tidak dikenal atau penjahat yang terkenal?'),
('t186', 'truth', 'Apa yang akan kamu lakukan jika hujan permen dari langit?'),
('t187', 'truth', 'Apa yang lebih menyenangkan: jadi hantu yang bisa jalan-jalan atau manusia dengan kekuatan super?'),
('t188', 'truth', 'Apa yang akan kamu lakukan jika semua impianmu jadi kenyataan besok?'),
('t189', 'truth', 'Apa yang lebih keren: naga peliharaan atau robot pembantu?'),
('t190', 'truth', 'Apa yang akan kamu bawa ke dunia fantasi favoritmu?'),
('t191', 'truth', 'Apa yang lebih penting di dunia fantasi: pedang ajaib atau jubah anti rusak?'),
('t192', 'truth', 'Apa yang akan kamu lakukan jika kamu bisa terbang tapi hanya 1 meter?'),
('t193', 'truth', 'Apa yang lebih seru: jadi karakter utama di film action atau film komedi?'),
('t194', 'truth', 'Apa yang akan kamu lakukan jika semua lampu di dunia padam permanen?'),
('t195', 'truth', 'Apa yang lebih keren: bisa bicara dengan hewan atau bisa bicara dengan tanaman?'),
('t196', 'truth', 'Apa yang akan kamu lakukan jika kamu bisa masuk ke dalam game?'),
('t197', 'truth', 'Apa yang lebih menyebalkan: alarm palsu hujan meteor atau kiamat palsu?'),
('t198', 'truth', 'Apa yang akan kamu lakukan jika semua makanan tiba-tiba hambar?'),
('t199', 'truth', 'Apa yang lebih menarik: mermaid di laut atau alien di luar angkasa?'),
('t200', 'truth', 'Apa yang akan kamu lakukan jika bisa teleport tapi hanya ke toilet?'),
('t201', 'truth', 'Apa teman masa kecil yang paling kamu ingat?'),
('t202', 'truth', 'Apa kenangan bermain paling seru waktu SD?'),
('t203', 'truth', 'Apa pelajaran paling berkesan waktu sekolah?'),
('t204', 'truth', 'Siapa guru paling berkesan dalam hidupmu?'),
('t205', 'truth', 'Apa kenangan liburan paling indah waktu kecil?'),
('t206', 'truth', 'Apa mainan favoritmu waktu kecil?'),
('t207', 'truth', 'Apa film kartun favoritmu waktu kecil?'),
('t208', 'truth', 'Apa cita-citamu waktu kecil dulu?'),
('t209', 'truth', 'Apa yang paling kamu rindukan dari masa SMA?'),
('t210', 'truth', 'Apa kenangan paling konyol waktu sekolah?'),
('t211', 'truth', 'Siapa teman pertama yang kamu kenal di sekolah?'),
('t212', 'truth', 'Apa yang paling kamu benci waktu sekolah?'),
('t213', 'truth', 'Apa prestasi sekolah yang paling kamu banggakan?'),
('t214', 'truth', 'Apa pelanggaran sekolah paling parah yang pernah kamu lakukan?'),
('t215', 'truth', 'Siapa yang paling populer di sekolahmu dulu?'),
('t216', 'truth', 'Apa yang paling kamu ingat dari guru galakmu?'),
('t217', 'truth', 'Apa yang paling membuatmu bersemangat waktu sekolah?'),
('t218', 'truth', 'Apa yang paling membuatmu takut waktu sekolah?'),
('t219', 'truth', 'Apa makanan kantin sekolah favoritmu?'),
('t220', 'truth', 'Apa kenangan paling manis waktu sekolah?'),
('t221', 'truth', 'Apa yang pertama kamu lakukan setelah lulus?'),
('t222', 'truth', 'Apa momen paling canggung waktu kuliah/sekolah?'),
('t223', 'truth', 'Apa yang akan kamu katakan ke dirimu yang masih sekolah?'),
('t224', 'truth', 'Apa pelajaran yang dulu kamu benci tapi sekarang berguna?'),
('t225', 'truth', 'Apa yang lebih sulit: ujian sekolah atau ujian kehidupan?'),
('t226', 'truth', 'Apa yang lebih berharga: ijazah atau pengalaman?'),
('t227', 'truth', 'Apa yang akan kamu lakukan jika bisa kembali ke bangku sekolah?'),
('t228', 'truth', 'Apa yang paling kamu syukuri dari masa sekolahmu?'),
('t229', 'truth', 'Apa yang tidak akan kamu ulangi dari masa sekolah?'),
('t230', 'truth', 'Apa hal terbaik yang diajarkan sekolah padamu?'),
('t231', 'truth', 'Siapa teman terdekatmu saat ini dan kenapa?'),
('t232', 'truth', 'Apa kualitas yang paling kamu cari dalam seorang teman?'),
('t233', 'truth', 'Apa hal yang paling menguji pertemananmu?'),
('t234', 'truth', 'Apa yang akan kamu lakukan jika temanmu mengkhianatimu?'),
('t235', 'truth', 'Apa yang lebih penting: punya banyak teman atau teman dekat yang sedikit?'),
('t236', 'truth', 'Apa pengalaman paling seru bareng teman-temanmu?'),
('t237', 'truth', 'Apa yang paling membuatmu kecewa sama teman?'),
('t238', 'truth', 'Apa yang akan kamu lakukan jika temanmu depresi?'),
('t239', 'truth', 'Apa yang lebih sulit: mencari teman baru atau menjaga teman lama?'),
('t240', 'truth', 'Apa yang diajarkan pertemanan padamu tentang hidup?'),
('t241', 'truth', 'Apa yang akan kamu lakukan jika kamu tidak punya teman sama sekali?'),
('t242', 'truth', 'Apa kualitas terburuk yang pernah kamu temui di seorang teman?'),
('t243', 'truth', 'Apa kualitas terbaik yang pernah kamu temui di seorang teman?'),
('t244', 'truth', 'Apa yang lebih kamu andalkan: teman atau keluarga?'),
('t245', 'truth', 'Apa yang akan kamu lakukan jika temanmu pindah ke luar negeri?'),
('t246', 'truth', 'Apa hal yang paling tidak kamu sukai dari pertemanan?'),
('t247', 'truth', 'Apa yang lebih menyakitkan: teman lupa ulang tahunmu atau teman lupa janji?'),
('t248', 'truth', 'Apa yang akan kamu lakukan jika temanmu naksir mantanmu?'),
('t249', 'truth', 'Apa yang lebih seru: liburan bareng teman atau liburan sendiri?'),
('t250', 'truth', 'Apa yang paling kamu inginkan dari pertemanan?'),
('t251', 'truth', 'Apa hal paling aneh yang pernah terjadi di rumahmu?'),
('t252', 'truth', 'Apa tradisi keluarga yang paling kamu suka?'),
('t253', 'truth', 'Siapa anggota keluarga yang paling dekat denganmu?'),
('t254', 'truth', 'Apa yang paling kamu syukuri dari keluargamu?'),
('t255', 'truth', 'Apa yang paling membuatmu kesal dari keluargamu?'),
('t256', 'truth', 'Apa momen paling lucu bareng keluargamu?'),
('t257', 'truth', 'Apa yang akan kamu lakukan jika keluargamu tidak setuju dengan pilihan hidupmu?'),
('t258', 'truth', 'Apa yang lebih penting: pendapat orang tua atau pendapatmu sendiri?'),
('t259', 'truth', 'Apa yang paling berat dari menjadi anak sulung/bungsu/tunggal?'),
('t260', 'truth', 'Apa yang diajarkan keluargamu yang paling berharga?'),
('t261', 'truth', 'Apa kenangan paling manis bersama orang tuamu?'),
('t262', 'truth', 'Apa yang akan kamu lakukan jika orang tuamu tidak mengerti dirimu?'),
('t263', 'truth', 'Apa yang lebih berharga: waktu bersama keluarga atau kebebasan?'),
('t264', 'truth', 'Apa yang akan kamu ubah dari keluargamu jika bisa?'),
('t265', 'truth', 'Apa yang paling kamu harapkan dari keluargamu?'),
('t266', 'truth', 'Apa yang akan kamu lakukan untuk membahagiakan orang tuamu?'),
('t267', 'truth', 'Apa yang lebih penting: membahagiakan orang tua atau dirimu sendiri?'),
('t268', 'truth', 'Apa kenangan paling sulit bersama keluargamu?'),
('t269', 'truth', 'Apa yang paling kamu rindukan dari rumah?'),
('t270', 'truth', 'Apa definisi "rumah" versimu?'),
('t271', 'truth', 'Apa rahasia terbesar yang kamu simpan dari orang tuamu?'),
('t272', 'truth', 'Apa yang akan kamu lakukan jika orang tuamu membaca chatmu?'),
('t273', 'truth', 'Apa yang lebih membuatmu nyaman: orang tua strict atau orang tua santai?'),
('t274', 'truth', 'Apa salah satu hal paling berani yang kamu lakukan tanpa sepengetahuan orang tua?'),
('t275', 'truth', 'Apa yang akan kamu lakukan jika orang tuamu tiba-tiba jadi temanmu?'),
('t276', 'truth', 'Apa momen paling emosional bersama keluargamu?'),
('t277', 'truth', 'Apa yang lebih penting: liburan mewah atau liburan sederhana bareng keluarga?'),
('t278', 'truth', 'Apa yang paling kamu pelajari dari orang tuamu?'),
('t279', 'truth', 'Apa yang akan kamu lakukan jika kamu jadi orang tua suatu hari nanti?'),
('t280', 'truth', 'Apa yang paling kamu sukai dari keluargamu?'),
('t281', 'truth', 'Apa yang paling membuatmu penasaran tentang kehidupan?'),
('t282', 'truth', 'Apa yang akan kamu tanyakan ke Tuhan jika bertemu?'),
('t283', 'truth', 'Apa yang lebih penting: agama atau moral?'),
('t284', 'truth', 'Apa yang kamu pikirkan tentang kehidupan setelah mati?'),
('t285', 'truth', 'Apa yang lebih membuatmu takut: kehilangan orang tersayang atau kehilangan dirimu sendiri?'),
('t286', 'truth', 'Apa arti kesuksesan menurutmu?'),
('t287', 'truth', 'Apa yang lebih penting: bekerja untuk hidup atau hidup untuk bekerja?'),
('t288', 'truth', 'Apa yang akan kamu lakukan jika uang bukan masalah?'),
('t289', 'truth', 'Apa yang lebih membuatmu bahagia: memberi atau menerima?'),
('t290', 'truth', 'Apa yang akan kamu lakukan jika semua orang di dunia baik padamu?'),
('t291', 'truth', 'Apa yang lebih buruk: perang atau kelaparan?'),
('t292', 'truth', 'Apa yang akan kamu lakukan untuk membuat dunia lebih baik?'),
('t293', 'truth', 'Apa yang lebih penting: keadilan atau kedamaian?'),
('t294', 'truth', 'Apa pendapatmu tentang konsep "takdir"?'),
('t295', 'truth', 'Apa yang lebih kuat: nasib atau pilihan?'),
('t296', 'truth', 'Apa yang akan kamu lakukan jika kamu adalah pemimpin dunia?'),
('t297', 'truth', 'Apa yang lebih berbahaya: teknologi atau kebodohan manusia?'),
('t298', 'truth', 'Apa yang lebih penting sekarang: lingkungan atau ekonomi?'),
('t299', 'truth', 'Apa yang akan kamu wariskan ke generasi berikutnya?'),
('t300', 'truth', 'Apa satu hal yang kamu ingin dunia tahu tentangmu?'),
('t301', 'truth', 'Apa yang paling membuatmu bersemangat dalam pekerjaan atau sekolah?'),
('t302', 'truth', 'Apa cita-cita terbesarmu saat ini?'),
('t303', 'truth', 'Apa yang lebih penting: gaji besar atau pekerjaan yang menyenangkan?'),
('t304', 'truth', 'Apa yang akan kamu lakukan jika kamu gagal mencapai impianmu?'),
('t305', 'truth', 'Apa yang lebih menentukan sukses: bakat atau kerja keras?'),
('t306', 'truth', 'Apa yang akan kamu lakukan jika bos/rekan kerjamu menyebalkan?'),
('t307', 'truth', 'Apa yang lebih penting: jenjang karir atau kesehatan mental?'),
('t308', 'truth', 'Apa yang paling membuatmu termotivasi?'),
('t309', 'truth', 'Apa yang akan kamu lakukan jika kamu punya usaha sendiri?'),
('t310', 'truth', 'Apa yang lebih memuaskan: diakui atau merasa berguna?'),
('t311', 'truth', 'Apa yang akan kamu lakukan jika tiba-tiba di-PHK?'),
('t312', 'truth', 'Apa yang lebih penting: networking atau skill?'),
('t313', 'truth', 'Apa yang paling ingin kamu pelajari untuk karirmu?'),
('t314', 'truth', 'Apa yang akan kamu lakukan jika punya kesempatan kerja di luar negeri?'),
('t315', 'truth', 'Apa yang lebih berharga: pengalaman kerja atau gelar akademik?'),
('t316', 'truth', 'Apa yang paling kamu takutkan dalam karirmu?'),
('t317', 'truth', 'Apa yang akan kamu lakukan jika harus memulai karir dari nol?'),
('t318', 'truth', 'Apa yang lebih penting: stabilitas atau pertumbuhan?'),
('t319', 'truth', 'Apa yang akan kamu lakukan jika punya waktu luang 1 jam setiap hari?'),
('t320', 'truth', 'Apa yang paling ingin kamu capai dalam 10 tahun ke depan?'),
('t321', 'truth', 'Apa yang akan kamu lakukan di tanggal 31 Desember malam?'),
('t322', 'truth', 'Apa resolusi tahun barumu yang paling realistis?'),
('t323', 'truth', 'Apa yang lebih penting: merayakan ulang tahun atau merayakan hidup?'),
('t324', 'truth', 'Apa hari libur favoritmu dan kenapa?'),
('t325', 'truth', 'Apa yang akan kamu lakukan jika ulang tahunmu dilupakan semua orang?'),
('t326', 'truth', 'Apa yang paling kamu suka dari musim hujan / kemarau?'),
('t327', 'truth', 'Apa yang lebih menyenangkan: merayakan kemenangan sendiri atau bersama orang lain?'),
('t328', 'truth', 'Apa tradisi favoritmu saat hari raya?'),
('t329', 'truth', 'Apa yang paling kamu rindukan dari hari raya waktu kecil?'),
('t330', 'truth', 'Apa yang akan kamu lakukan jika setiap hari adalah hari libur?'),
('t331', 'truth', 'Apa kencan impianmu yang paling sederhana?'),
('t332', 'truth', 'Apa yang lebih romantis: makan malam mewah atau piknik santai?'),
('t333', 'truth', 'Apa yang akan kamu lakukan untuk pacar saat dia sedang sedih?'),
('t334', 'truth', 'Apa yang lebih penting: surprise atau konsisten?'),
('t335', 'truth', 'Apa yang akan kamu lakukan jika pasanganmu sibuk terus?'),
('t336', 'truth', 'Apa bahasa cinta yang paling kamu pahami?'),
('t337', 'truth', 'Apa yang lebih manis: pujian di depan orang atau pujian pribadi?'),
('t338', 'truth', 'Apa yang akan kamu lakukan jika pasanganmu lupa anniversary?'),
('t339', 'truth', 'Apa yang lebih indah: sunset bareng atau hujan bareng?'),
('t340', 'truth', 'Apa yang akan kamu lakukan jika pasanganmu lebih sukses darimu?'),
('t341', 'truth', 'Apa batasan yang paling penting dalam hubungan?'),
('t342', 'truth', 'Apa yang lebih penting: setia atau jujur?'),
('t343', 'truth', 'Apa yang akan kamu lakukan jika pasanganmu punya teman dekat lawan jenis?'),
('t344', 'truth', 'Apa yang lebih menantang: pacaran beda agama atau beda negara?'),
('t345', 'truth', 'Apa yang akan kamu lakukan jika pasanganmu tidak pernah bilang "I love you"?'),
('t346', 'truth', 'Apa yang lebih penting: percaya atau kontrol?'),
('t347', 'truth', 'Apa yang akan kamu lakukan jika pasanganmu ketahuan bohong?'),
('t348', 'truth', 'Apa yang lebih berat: memaafkan atau dipercaya lagi?'),
('t349', 'truth', 'Apa yang akan kamu lakukan jika cinta pertamamu datang lagi?'),
('t350', 'truth', 'Apa yang lebih penting dalam pasangan: dewasa atau seru?'),
('t351', 'truth', 'Apa hal paling berani yang pernah kamu lakukan di ranjang?'),
('t352', 'truth', 'Apa fantasi terliarmu yang belum terwujud?'),
('t353', 'truth', 'Apa yang lebih penting dalam hubungan fisik: koneksi emosional atau teknis?'),
('t354', 'truth', 'Apa yang akan kamu lakukan jika pasanganmu minta sesuatu yang ekstrem di ranjang?'),
('t355', 'truth', 'Apa yang lebih mengasyikkan: foreplay atau climax?'),
('t356', 'truth', 'Apa turn on terbesarmu?'),
('t357', 'truth', 'Apa turn off terbesarmu?'),
('t358', 'truth', 'Apa yang akan kamu lakukan jika pasanganmu punya fetish aneh?'),
('t359', 'truth', 'Apa yang lebih penting: ukuran atau teknik?'),
('t360', 'truth', 'Apa yang akan kamu lakukan jika tidak puas secara seksual?'),
('t361', 'truth', 'Apa yang lebih berani: kirim foto seksi atau bilang "aku mau" duluan?'),
('t362', 'truth', 'Apa yang akan kamu lakukan jika ketahuan nonton film biru?'),
('t363', 'truth', 'Apa yang lebih memalukan: ketahuan pacaran atau ketahuan masturbasi?'),
('t364', 'truth', 'Apa yang akan kamu lakukan jika pasanganmu minta roleplay?'),
('t365', 'truth', 'Apa yang lebih penting: kepuasan sendiri atau kepuasan pasangan?'),
('t366', 'truth', 'Apa yang paling berani ingin kamu coba di ranjang?'),
('t367', 'truth', 'Apa yang akan kamu lakukan jika pasanganmu lebih berpengalaman darimu?'),
('t368', 'truth', 'Apa yang lebih bikin greget: rayuan verbal atau sentuhan fisik?'),
('t369', 'truth', 'Apa yang akan kamu lakukan jika libido pasanganmu berbeda denganmu?'),
('t370', 'truth', 'Apa yang lebih seksi: percaya diri atau misterius?'),
('t371', 'truth', 'Apa rahasia yang paling sulit kamu jaga?'),
('t372', 'truth', 'Apa yang akan kamu lakukan jika tahu semua orang punya akses ke pikiranmu?'),
('t373', 'truth', 'Apa yang lebih buruk: ketahuan selingkuh atau ketahuan korupsi?'),
('t374', 'truth', 'Apa yang akan kamu lakukan jika menemukan barang bukti pasangan selingkuh?'),
('t375', 'truth', 'Apa yang lebih pedih: ditolak atau diabaikan?'),
('t376', 'truth', 'Apa yang akan kamu lakukan jika tahu temanmu membicarakanmu di belakang?'),
('t377', 'truth', 'Apa yang lebih sakit: dikhianati atau dibohongi?'),
('t378', 'truth', 'Apa yang akan kamu lakukan jika tahu seseorang menyimpan perasaan padamu?'),
('t379', 'truth', 'Apa yang lebih buruk: menyakiti orang lain atau menyakiti diri sendiri?'),
('t380', 'truth', 'Apa yang akan kamu lakukan jika punya kesempatan balas dendam?'),
('t381', 'truth', 'Apa yang lebih memalukan: pakaian dalam sobek di tempat umum atau salah kamar mandi?'),
('t382', 'truth', 'Apa yang akan kamu lakukan jika salah kirim foto pribadi?'),
('t383', 'truth', 'Apa yang lebih memalukan: muntah di pesta atau ketahuan lagi nguping?'),
('t384', 'truth', 'Apa yang akan kamu lakukan jika ketahuan pacaran sama guru/bos?'),
('t385', 'truth', 'Apa yang lebih memalukan: terjatuh di depan gebetan atau ketahuan lagi kentut?'),
('t386', 'truth', 'Apa yang akan kamu lakukan jika foto masa lalumu yang memalukan viral?'),
('t387', 'truth', 'Apa yang lebih menyakitkan: diketawain atau diacuhkan?'),
('t388', 'truth', 'Apa yang akan kamu lakukan jika mantanmu menyebarkan rahasiamu?'),
('t389', 'truth', 'Apa yang lebih memalukan: orang tua lihat kamu lagi PDKT atau lihat kamu lagi berantem?'),
('t390', 'truth', 'Apa yang akan kamu lakukan jika ketahuan masih suka sama mantan?'),
('t391', 'truth', 'Apa yang lebih penting: penampilan fisik atau kesehatan?'),
('t392', 'truth', 'Apa yang akan kamu lakukan jika berat badanmu naik 20 kg dalam sebulan?'),
('t393', 'truth', 'Apa yang lebih membuatmu insecure: wajah atau tubuh?'),
('t394', 'truth', 'Apa yang akan kamu lakukan jika semua standar kecantikan dihapus?'),
('t395', 'truth', 'Apa yang lebih penting: diet atau olahraga?'),
('t396', 'truth', 'Apa yang paling kamu syukuri dari tubuhmu?'),
('t397', 'truth', 'Apa yang akan kamu ubah dari penampilanmu jika bisa?'),
('t398', 'truth', 'Apa yang lebih percaya diri: makeup natural atau full glam?'),
('t399', 'truth', 'Apa yang akan kamu lakukan jika botak di usia muda?'),
('t400', 'truth', 'Apa yang lebih penting: pakaian branded atau nyaman dipakai?'),
('t401', 'truth', 'Apa hal paling nakal yang pernah kamu lakukan saat masih sendiri?'),
('t402', 'truth', 'Apa yang akan kamu lakukan jika tidak ada yang tahu apa yang kamu lakukan?'),
('t403', 'truth', 'Apa yang lebih menggoda: godaan fisik atau godaan materi?'),
('t404', 'truth', 'Apa yang akan kamu lakukan jika tahu tidak akan ketahuan?'),
('t405', 'truth', 'Apa yang paling liar yang pernah kamu lakukan di tempat umum?'),
('t406', 'truth', 'Apa yang lebih berbahaya: main api atau main hati?'),
('t407', 'truth', 'Apa yang akan kamu lakukan jika jadi orang paling menarik di dunia?'),
('t408', 'truth', 'Apa satu malam paling liar yang pernah kamu alami?'),
('t409', 'truth', 'Apa yang lebih menggairahkan: bahaya atau misteri?'),
('t410', 'truth', 'Apa yang akan kamu lakukan jika tidak ada konsekuensi hukum?'),
('t411', 'truth', 'Apa yang paling berani kamu lakukan untuk mendapatkan perhatian seseorang?'),
('t412', 'truth', 'Apa yang lebih memabukkan: alkohol atau cinta?'),
('t413', 'truth', 'Apa yang akan kamu lakukan jika semua orang menuruti kemauanmu?'),
('t414', 'truth', 'Apa yang lebih menyenangkan: goda yang menggoda atau yang digoda?'),
('t415', 'truth', 'Apa yang akan kamu lakukan di klub malam tanpa pengenal?'),
('t416', 'truth', 'Apa kebebasan paling liar yang ingin kamu rasakan?'),
('t417', 'truth', 'Apa yang lebih liar: liburan tanpa rencana atau kencan buta?'),
('t418', 'truth', 'Apa yang akan kamu lakukan jika semua larangan sosial dihapus?'),
('t419', 'truth', 'Apa yang lebih seru: punya rahasia atau tahu rahasia orang?'),
('t420', 'truth', 'Apa yang akan kamu lakukan jika bisa berganti identitas selama seminggu?'),
('t421', 'truth', 'Apa yang lebih menggoda: ex yang tiba-tiba chat atau teman yang tiba-tiba perhatian?'),
('t422', 'truth', 'Apa yang akan kamu lakukan jika gebetanmu tiba-tiba nembak?'),
('t423', 'truth', 'Apa yang lebih sulit: move on atau nembak?'),
('t424', 'truth', 'Apa yang akan kamu lakukan jika gebetanmu tidak peka?'),
('t425', 'truth', 'Apa yang lebih manis: ditembak langsung atau di-kode-kode dulu?'),
('t426', 'truth', 'Apa yang akan kamu lakukan jika gebetanmu terlalu sibuk?'),
('t427', 'truth', 'Apa yang lebih bikin deg-degan: nunggu balasan chat atau nunggu dia muncul?'),
('t428', 'truth', 'Apa yang akan kamu lakukan kalau gebetan suka sama temanmu?'),
('t429', 'truth', 'Apa yang lebih menyenangkan: fase PDKT atau fase pacaran?'),
('t430', 'truth', 'Apa yang akan kamu lakukan jika gebetanmu punya pasangan?'),
('t431', 'truth', 'Apa yang akan kamu lakukan jika kamu bisa menjadi orang lain selama sehari?'),
('t432', 'truth', 'Apa yang lebih menantang: mendaki gunung atau memulai bisnis?'),
('t433', 'truth', 'Apa yang akan kamu lakukan jika semua keinginanmu terwujud tapi kamu lupa?'),
('t434', 'truth', 'Apa yang lebih menakutkan: kehilangan ingatan atau kehilangan identitas?'),
('t435', 'truth', 'Apa yang akan kamu lakukan jika kamu punya kloningan?'),
('t436', 'truth', 'Apa yang lebih seru: hidup di masa lalu atau masa depan?'),
('t437', 'truth', 'Apa yang akan kamu lakukan jika usia biologismu berhenti di 25?'),
('t438', 'truth', 'Apa yang lebih menantang: hidup sendiri di alam liar atau hidup di kota asing?'),
('t439', 'truth', 'Apa yang akan kamu lakukan jika seluruh dunia menggunakan satu bahasa?'),
('t440', 'truth', 'Apa yang lebih berkesan: perjalanan atau tujuan?'),
('t441', 'truth', 'Apa yang paling membingungkan bagimu tentang kehidupan?'),
('t442', 'truth', 'Apa yang akan kamu lakukan jika semua pertanyaan punya jawaban?'),
('t443', 'truth', 'Apa yang lebih mengesankan: kepintaran atau kebijaksanaan?'),
('t444', 'truth', 'Apa yang akan kamu lakukan jika kamu menemukan buku yang berisi masa depanmu?'),
('t445', 'truth', 'Apa yang lebih penting: logika atau intuisi?'),
('t446', 'truth', 'Apa yang akan kamu lakukan jika semua orang setuju denganmu?'),
('t447', 'truth', 'Apa yang lebih membentukmu: alam atau pengasuhan?'),
('t448', 'truth', 'Apa yang akan kamu lakukan jika kamu bisa menghentikan waktu?'),
('t449', 'truth', 'Apa yang lebih berbahaya: terlalu percaya atau terlalu curiga?'),
('t450', 'truth', 'Apa yang akan kamu lakukan jika tahu kapan kamu akan mati?'),
('t451', 'truth', 'Apa yang akan kamu lakukan jika semua orang di bumi jadi zombie kecuali kamu?'),
('t452', 'truth', 'Apa yang lebih penting: bertahan hidup atau mempertahankan kemanusiaan?'),
('t453', 'truth', 'Apa yang akan kamu lakukan jika bencana alam besar terjadi besok?'),
('t454', 'truth', 'Apa yang lebih kamu takuti: bencana alam buatan atau bencana alam alami?'),
('t455', 'truth', 'Apa yang akan kamu lakukan jika kamu terdampar di planet asing?'),
('t456', 'truth', 'Apa yang lebih menakutkan: alien yang jahat atau alien yang baik tapi aneh?'),
('t457', 'truth', 'Apa yang akan kamu lakukan jika AI mengambil alih pekerjaanmu?'),
('t458', 'truth', 'Apa yang lebih mengkhawatirkan: AI terlalu pintar atau manusia terlalu bodoh?'),
('t459', 'truth', 'Apa yang akan kamu lakukan jika peradaban runtuh besok?'),
('t460', 'truth', 'Apa yang lebih penting dalam kiamat: senjata atau persediaan makanan?'),
('t461', 'truth', 'Apa yang akan kamu lakukan jika semua orang jadi saling jujur?'),
('t462', 'truth', 'Apa yang lebih penting: privasi atau transparansi?'),
('t463', 'truth', 'Apa yang akan kamu lakukan jika media sosial lenyap besok?'),
('t464', 'truth', 'Apa yang lebih berbahaya: media sosial atau rokok?'),
('t465', 'truth', 'Apa yang akan kamu lakukan jika semua tagihan dihapus?'),
('t466', 'truth', 'Apa yang lebih membuatmu cemas: masa depan pribadi atau masa depan dunia?'),
('t467', 'truth', 'Apa yang akan kamu lakukan jika semua energi fosil habis?'),
('t468', 'truth', 'Apa yang lebih penting sekarang: inovasi atau konservasi?'),
('t469', 'truth', 'Apa yang akan kamu lakukan jika semua orang hidup sampai 200 tahun?'),
('t470', 'truth', 'Apa yang lebih menakutkan: overpopulasi atau populasi menurun?'),
('t471', 'truth', 'Apa dampak terbesar teknologi pada hidupmu?'),
('t472', 'truth', 'Apa yang lebih kamu andalkan: Google atau otakmu?'),
('t473', 'truth', 'Apa yang akan kamu lakukan jika internet mati permanen?'),
('t474', 'truth', 'Apa yang lebih membuatmu kecanduan: ponsel atau game?'),
('t475', 'truth', 'Apa yang akan kamu lakukan jika semua data pribadimu bocor?'),
('t476', 'truth', 'Apa yang lebih menakutkan: kehilangan data atau kehilangan privasi?'),
('t477', 'truth', 'Apa yang akan kamu lakukan jika teknologi bisa membaca emosi?'),
('t478', 'truth', 'Apa yang lebih penting: kemajuan teknologi atau kesehatan mental?'),
('t479', 'truth', 'Apa yang akan kamu lakukan jika kamu bisa upload ingatan ke cloud?'),
('t480', 'truth', 'Apa yang lebih menarik: realitas virtual atau realitas yang diperkaya?'),
('t481', 'truth', 'Apa yang akan kamu lakukan jika semua orang mengingat satu kesalahan terbesarmu?'),
('t482', 'truth', 'Apa yang lebih membuatmu marah: ketidakadilan atau kebodohan?'),
('t483', 'truth', 'Apa yang akan kamu lakukan jika semua orang di dunia membutuhkanmu?'),
('t484', 'truth', 'Apa yang lebih menguras energi: drama atau pekerjaan?'),
('t485', 'truth', 'Apa yang akan kamu lakukan jika tidak ada yang namanya "uang"?'),
('t486', 'truth', 'Apa yang lebih menakutkan: hidup tanpa aturan atau hidup terlalu diatur?'),
('t487', 'truth', 'Apa yang akan kamu lakukan jika kebahagiaan bisa diukur dan dilihat semua orang?'),
('t488', 'truth', 'Apa yang lebih penting: bebas atau aman?'),
('t489', 'truth', 'Apa yang akan kamu lakukan jika semua orang punya kemampuan yang sama?'),
('t490', 'truth', 'Apa yang lebih tidak adil: lahir miskin atau lahir cacat?'),
('t491', 'truth', 'Apa satu pertanyaan yang paling ingin kamu jawab dengan jujur?'),
('t492', 'truth', 'Apa yang akan kamu lakukan jika kamu adalah orang paling bijaksana di dunia?'),
('t493', 'truth', 'Apa yang lebih berharga: 1 juta rupiah atau 1 menit bersama orang tersayang?'),
('t494', 'truth', 'Apa yang akan kamu lakukan jika semua orang mengenalmu tapi kau tak kenal mereka?'),
('t495', 'truth', 'Apa yang lebih membuatmu berarti: apa yang kamu miliki atau apa yang kamu berikan?'),
('t496', 'truth', 'Apa yang akan kamu lakukan jika kamu adalah jawaban dari doa seseorang?'),
('t497', 'truth', 'Apa yang lebih penting: meninggalkan warisan atau meninggalkan kenangan?'),
('t498', 'truth', 'Apa yang akan kamu lakukan jika hidup ini adalah simulasi?'),
('t499', 'truth', 'Apa yang akan kamu lakukan jika kamu bisa merasakan apa yang orang lain rasakan?'),
('t500', 'truth', 'Apa satu kata yang bisa menggambarkan hidupmu saat ini?');
