/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as JoinRoomRouteImport } from './routes/join-room'
import { Route as CreateRoomRouteImport } from './routes/create-room'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomIdRouteImport } from './routes/room.$id'
import { Route as RoomIdGameRouteImport } from './routes/room.$id.game'

const JoinRoomRoute = JoinRoomRouteImport.update({
  id: '/join-room',
  path: '/join-room',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoomRoute = CreateRoomRouteImport.update({
  id: '/create-room',
  path: '/create-room',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdRoute = RoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdGameRoute = RoomIdGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => RoomIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/join-room': typeof JoinRoomRoute
  '/room/$id': typeof RoomIdRouteWithChildren
  '/room/$id/game': typeof RoomIdGameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/join-room': typeof JoinRoomRoute
  '/room/$id': typeof RoomIdRouteWithChildren
  '/room/$id/game': typeof RoomIdGameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/join-room': typeof JoinRoomRoute
  '/room/$id': typeof RoomIdRouteWithChildren
  '/room/$id/game': typeof RoomIdGameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-room'
    | '/join-room'
    | '/room/$id'
    | '/room/$id/game'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-room' | '/join-room' | '/room/$id' | '/room/$id/game'
  id:
    | '__root__'
    | '/'
    | '/create-room'
    | '/join-room'
    | '/room/$id'
    | '/room/$id/game'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoomRoute: typeof CreateRoomRoute
  JoinRoomRoute: typeof JoinRoomRoute
  RoomIdRoute: typeof RoomIdRouteWithChildren
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/join-room': {
      id: '/join-room'
      path: '/join-room'
      fullPath: '/join-room'
      preLoaderRoute: typeof JoinRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-room': {
      id: '/create-room'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof CreateRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$id': {
      id: '/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$id/game': {
      id: '/room/$id/game'
      path: '/game'
      fullPath: '/room/$id/game'
      preLoaderRoute: typeof RoomIdGameRouteImport
      parentRoute: typeof RoomIdRoute
    }
  }
}

interface RoomIdRouteChildren {
  RoomIdGameRoute: typeof RoomIdGameRoute
}

const RoomIdRouteChildren: RoomIdRouteChildren = {
  RoomIdGameRoute: RoomIdGameRoute,
}

const RoomIdRouteWithChildren =
  RoomIdRoute._addFileChildren(RoomIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoomRoute: CreateRoomRoute,
  JoinRoomRoute: JoinRoomRoute,
  RoomIdRoute: RoomIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
